---
# https://github.com/rbenv/rbenv#basic-github-checkout
# https://blakewilliams.me/posts/system-wide-rbenv-install
- name: Checkout rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ rbenv_path }}"
- name: Build rbenv
  shell:
    cmd: src/configure && make -C src
    chdir: "{{ rbenv_path }}"
- name: Add rbenv to $PATH
  blockinfile:
    path: /etc/profile
    block: |
      # rbenv initialization
      {{ rbenv_init }}
- name: Checkout ruby-buld
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ rbenv_path }}/plugins/ruby-build"
- name: Install Ruby {{ ruby_version }}
  shell: |
    {{ rbenv_init }}
    rbenv install {{ ruby_version }}
    rbenv global {{ ruby_version }}
