---
# https://github.com/nodesource/distributions
- name: Install NodeSource Node.js {{ node_major_version }}
  shell: curl -sL https://rpm.nodesource.com/setup_{{ node_major_version }}.x | sudo bash -
  args:
    warn: no
- name: Install Node.js {{ node_major_version }}
  package:
    name:
      - nodejs
