---
- name: Enable install Nginx
  shell: amazon-linux-extras enable nginx1
- name: Install Nginx
  package:
    name: nginx
    state: present
- name: Start service Nginx, if not started
  service:
    name: nginx
    state: started
    enabled: yes
