name: Serverspec

on: [push, pull_request]

jobs:
  build:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    runs-on: macos-10.15

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Ansible
      run: |
        brew install ansible
        ansible --version
    - name: Build Vagrant Box with Packer
      run: |
        packer build -force -only=vagrant packer/rails.json
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install libraries
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run Serverspec
      run: bundle exec rake spec
